server:
  port: 8090


spring:
  application:
    name: nacos-service
  cloud:
    discovery:
      server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'