server:
  port: 8091


spring:
  application:
    name: nacos-service
  cloud:
    discovery:
      service-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'