server:
  port: 8081

spring:
  application:
    name: ribbo-service


user-security:
  name: admin #需要注册的注册中心的security的账户
  passwd: 123456 #需要注册的注册中心security的密码
  hostname: localhost #需要注册的注册中心服务部署的路径
  port1: 7002 #需要注册的注册中心的端口号
  port2: 7003 #需要注册的注册中心的端口号

eureka:
  client:
    register-with-eureka: true #指定是否要注册到注册中心（允许注册到注册中心）
    fetch-registry: true #指定是否要从注册中心获取服务（允许获取服务）
    service-url:
      defaultZone: http://${user-security.name}:${user-security.passwd}@${user-security.hostname}:${user-security.port1}/eureka/,http://${user-security.name}:${user-security.passwd}@${user-security.hostname}:${user-security.port1}/eureka/
    registry-fetch-interval-seconds: 3 #定义去eureka服务端获取服务列表的时间间隔
  instance:
    lease-expiration-duration-in-seconds: 5 #定义服务多久不去续约认为服务失效
    lease-renewal-interval-in-seconds: 3 #定义服务多久去注册中心续约


ribbon:
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: true #对超时请求启用重试机制
  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
  MaxAutoRetries: 1 # 切换实例后重试最大次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法
