service-url:
  user-service: http://localhost:8085
  user-hystrix: http://localhost:8082


spring:
  cloud:
    gateway:
      routes:
#        - id: add_request_parameter_route #路由的ID
#          uri: ${service-url.user-hystrix} #匹配后路由地址
#          filters:
#            - AddRequestParameter=a, 1
#          predicates: # 断言，路径相匹配的进行路由
#            - Path=/Hystrix/**
#            - Method=GET
#        - id: stripprefix_route #路由的ID
#          uri: ${service-url.user-hystrix} #匹配后路由地址
#          filters:
#            - StripPrefix=2
#          predicates: # 断言，路径相匹配的进行路由
#            - Path=/gateway/hystrix-service/Hystrix/**
#            - Method=GET
#        - id: prefixpath_route #路由的ID
#          uri: ${service-url.user-hystrix} #匹配后路由地址
#          filters:
#            - PrefixPath=/Hystrix
#          predicates: # 断言，路径相匹配的进行路由
#            - Method=GET
#        - id: hystrix_route #路由的ID
#          uri: ${service-url.user-hystrix} #匹配后路由地址
#          filters:
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback
#          predicates: # 断言，路径相匹配的进行路由
#            - Path=/Hystrix/**
#            - Method=GET
        - id: retry_route #路由的ID
          uri: ${service-url.user-hystrix} #匹配后路由地址
          filters:
            - name: Retry
              args:
                retries: 1 #需要进行重试的次数
                statuses: BAD_GATEWAY #返回哪个状态码需要进行重试，返回状态码为5XX进行重试
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
          predicates: # 断言，路径相匹配的进行路由
            - Path=/Hystrix/**
            - Method=GET

